import type { CognitiveNode } from "../types/memory";
import type { MemoryStats, AuditEntry, RecallResponse, ReflectResponse } from "../types/api";

export const MOCK_SPACE_ID = "space_mock_memory_ui";

/**
 * Mock data manifest for UI testing.
 *
 * Covers: 01_ingestion, 02_contradiction, 03_consolidation, 04_locomo,
 * 05_lifecycle, 07_modeling, 08_qul
 *
 * Each node maps to a verification trajectory as described in
 * examples/agent_memory/ANALYSIS.md
 */

export const MOCK_NODES: CognitiveNode[] = [
  // ===== 01_ingestion_pipeline =====
  {
    id: "mem:observation:mock:01",
    content: "客户近3个月内负面舆情发生2次，担保链深度为4",
    memoryType: "observation",
    cognitiveLayer: "perception",
    beliefStatus: "accepted",
    confidence: 0.92,
    visibility: "shared",
    createdBy: "ingestion_pipeline",
    spaceId: MOCK_SPACE_ID,
    tags: ["ingestion", "T1"],
    attributes: { source_trust_tier: "tier2" },
    modelDomain: "world",
    sourceTrustTier: "tier2",
    recordedAt: "2026-05-06T10:00:00Z",
  },
  {
    id: "mem:observation:mock:02",
    content: "DeduplicationGate 检测到完全相同的输入，复用 node_id",
    memoryType: "observation",
    cognitiveLayer: "perception",
    beliefStatus: "accepted",
    confidence: 0.95,
    visibility: "shared",
    createdBy: "ingestion_pipeline",
    spaceId: MOCK_SPACE_ID,
    tags: ["ingestion", "T2", "dedup"],
    attributes: { dedup_count: 3 },
    modelDomain: "world",
    sourceTrustTier: "tier2",
    recordedAt: "2026-05-06T10:05:00Z",
  },
  {
    id: "mem:entity:mock:03",
    content: "SUP_R_012 供应商实体",
    memoryType: "entity",
    cognitiveLayer: "semantic",
    beliefStatus: "accepted",
    confidence: 0.88,
    visibility: "shared",
    createdBy: "entity_resolver",
    spaceId: MOCK_SPACE_ID,
    tags: ["ingestion", "T3", "L1_exact"],
    attributes: { resolution: "L1_exact_match" },
    modelDomain: "task",
    sourceTrustTier: "tier1",
    recordedAt: "2026-05-06T10:10:00Z",
  },
  {
    id: "mem:entity:mock:04",
    content: "SUP_R_044 供应商实体 (trigram模糊匹配)",
    memoryType: "entity",
    cognitiveLayer: "semantic",
    beliefStatus: "pending_review",
    confidence: 0.72,
    visibility: "shared",
    createdBy: "entity_resolver",
    spaceId: MOCK_SPACE_ID,
    tags: ["ingestion", "T4", "L2_trigram"],
    attributes: { resolution: "L2_trigram_match" },
    modelDomain: "task",
    sourceTrustTier: "tier2",
    recordedAt: "2026-05-06T10:15:00Z",
  },

  // ===== 02_contradiction_belief =====
  {
    id: "mem:opinion:mock:05",
    content: "供应商信用评级为D级，不适合合作",
    memoryType: "opinion",
    cognitiveLayer: "opinion",
    beliefStatus: "accepted",
    confidence: 0.85,
    visibility: "shared",
    createdBy: "analyst_A",
    spaceId: MOCK_SPACE_ID,
    tags: ["contradiction", "T1", "rule_based"],
    attributes: { severity: "high" },
    modelDomain: "world",
    sourceTrustTier: "tier1",
    recordedAt: "2026-05-06T10:20:00Z",
  },
  {
    id: "mem:opinion:mock:06",
    content: "供应商信用评级不是D级，可以继续合作",
    memoryType: "opinion",
    cognitiveLayer: "opinion",
    beliefStatus: "accepted",
    confidence: 0.80,
    visibility: "shared",
    createdBy: "analyst_B",
    spaceId: MOCK_SPACE_ID,
    tags: ["contradiction", "T1", "contradicts"],
    attributes: { severity: "high" },
    modelDomain: "world",
    sourceTrustTier: "tier2",
    recordedAt: "2026-05-06T10:22:00Z",
  },
  {
    id: "mem:opinion:mock:07",
    content: "从语义角度看，两个分析师的结论相互矛盾，需要进一步核实信用评级",
    memoryType: "opinion",
    cognitiveLayer: "opinion",
    beliefStatus: "pending_review",
    confidence: 0.65,
    visibility: "shared",
    createdBy: "semantic_contradiction_detector",
    spaceId: MOCK_SPACE_ID,
    tags: ["contradiction", "T2", "semantic"],
    attributes: { severity: "medium", method: "semantic_similarity" },
    modelDomain: "world",
    sourceTrustTier: "tier2",
    recordedAt: "2026-05-06T10:25:00Z",
  },
  {
    id: "mem:opinion:mock:08",
    content: "旧策略: 担保链深度>3 时触发预警",
    memoryType: "opinion",
    cognitiveLayer: "opinion",
    beliefStatus: "superseded",
    confidence: 0.70,
    visibility: "shared",
    createdBy: "policy_engine",
    spaceId: MOCK_SPACE_ID,
    tags: ["contradiction", "T3", "supersede"],
    attributes: {},
    modelDomain: "task",
    sourceTrustTier: "tier1",
    supersededBy: "mem:opinion:mock:09",
    recordedAt: "2026-05-06T10:28:00Z",
  },
  {
    id: "mem:opinion:mock:09",
    content: "新策略: 担保链深度>4 且负面舆情>=2 时触发预警",
    memoryType: "opinion",
    cognitiveLayer: "opinion",
    beliefStatus: "accepted",
    confidence: 0.87,
    visibility: "shared",
    createdBy: "policy_engine",
    spaceId: MOCK_SPACE_ID,
    tags: ["contradiction", "T3", "supersede_target"],
    attributes: { supersedes: "mem:opinion:mock:08" },
    modelDomain: "task",
    sourceTrustTier: "tier1",
    recordedAt: "2026-05-06T10:30:00Z",
  },

  // ===== 03_consolidation_compilation =====
  {
    id: "mem:fragment:mock:10",
    content: "碎片: 供应商最近一次交货延迟了3天",
    memoryType: "fragment",
    cognitiveLayer: "perception",
    beliefStatus: "accepted",
    confidence: 0.75,
    visibility: "shared",
    createdBy: "consolidation_engine",
    spaceId: MOCK_SPACE_ID,
    tags: ["consolidation", "T1"],
    attributes: {},
    modelDomain: "task",
    sourceTrustTier: "tier2",
    recordedAt: "2026-05-06T10:35:00Z",
  },
  {
    id: "mem:fragment:mock:11",
    content: "碎片: 供应商最近一次质量问题投诉增加了50%",
    memoryType: "fragment",
    cognitiveLayer: "perception",
    beliefStatus: "accepted",
    confidence: 0.78,
    visibility: "shared",
    createdBy: "consolidation_engine",
    spaceId: MOCK_SPACE_ID,
    tags: ["consolidation", "T1"],
    attributes: {},
    modelDomain: "task",
    sourceTrustTier: "tier2",
    recordedAt: "2026-05-06T10:36:00Z",
  },
  {
    id: "mem:observation:mock:12",
    content: "综合评估: 供应商履约能力显著下降，交付延迟且质量投诉增加，建议重新评估合作关系",
    memoryType: "observation",
    cognitiveLayer: "perception",
    beliefStatus: "accepted",
    confidence: 0.82,
    visibility: "shared",
    createdBy: "consolidation_engine",
    spaceId: MOCK_SPACE_ID,
    tags: ["consolidation", "T1", "consolidated"],
    attributes: {
      source_fragment_ids: "mem:fragment:mock:10,mem:fragment:mock:11",
    },
    modelDomain: "task",
    sourceTrustTier: "tier1",
    recordedAt: "2026-05-06T10:40:00Z",
  },

  // ===== 04_locomo =====
  {
    id: "mem:observation:mock:13",
    content: "深圳分部的供应商风险评级调整为高风险",
    memoryType: "observation",
    cognitiveLayer: "perception",
    beliefStatus: "accepted",
    confidence: 0.90,
    visibility: "shared",
    createdBy: "locomo_eval",
    spaceId: MOCK_SPACE_ID,
    tags: ["locomo", "T1", "single_hop"],
    attributes: { location: "shenzhen" },
    modelDomain: "world",
    sourceTrustTier: "tier1",
    recordedAt: "2026-05-06T10:45:00Z",
  },
  {
    id: "mem:observation:mock:14",
    content: "深圳分部和北京分部的最新采购策略已从本地采购切换为全国集中采购",
    memoryType: "observation",
    cognitiveLayer: "perception",
    beliefStatus: "accepted",
    confidence: 0.88,
    visibility: "shared",
    createdBy: "locomo_eval",
    spaceId: MOCK_SPACE_ID,
    tags: ["locomo", "T2", "multi_hop"],
    attributes: { related_entities: "shenzhen,beijing" },
    modelDomain: "task",
    sourceTrustTier: "tier1",
    recordedAt: "2026-05-06T10:48:00Z",
  },
  {
    id: "mem:observation:mock:15",
    content: "最新策略: 全国集中采购模式已生效，替代了本地采购策略",
    memoryType: "observation",
    cognitiveLayer: "perception",
    beliefStatus: "accepted",
    confidence: 0.91,
    visibility: "shared",
    createdBy: "locomo_eval",
    spaceId: MOCK_SPACE_ID,
    tags: ["locomo", "T3", "temporal"],
    attributes: { version: "v2.0", effective_date: "2026-05-01" },
    modelDomain: "task",
    sourceTrustTier: "tier1",
    recordedAt: "2026-05-06T10:50:00Z",
  },

  // ===== 05_lifecycle_governance =====
  {
    id: "mem:observation:mock:16",
    content: "QUL生命周期验证: memory强度因子包括 confirmation(0.15) + correction(0.15) + citation(0.10) + recency(0.30) + cohesion(0.30)",
    memoryType: "observation",
    cognitiveLayer: "perception",
    beliefStatus: "accepted",
    confidence: 0.85,
    visibility: "shared",
    createdBy: "lifecycle_eval",
    spaceId: MOCK_SPACE_ID,
    tags: ["lifecycle", "T1"],
    attributes: { confirmation_count: "3", memory_strength: "0.78" },
    modelDomain: "world",
    sourceTrustTier: "tier1",
    recordedAt: "2026-05-06T11:00:00Z",
  },
  {
    id: "mem:observation:mock:17",
    content: "MCP接口验证: 完整生命周期追踪，从ingestion到DreamCycle",
    memoryType: "observation",
    cognitiveLayer: "perception",
    beliefStatus: "accepted",
    confidence: 0.88,
    visibility: "shared",
    createdBy: "lifecycle_mcp",
    spaceId: MOCK_SPACE_ID,
    tags: ["lifecycle", "T5", "mcp"],
    attributes: { lifecycle_stages: "5/5" },
    modelDomain: "self",
    sourceTrustTier: "tier1",
    recordedAt: "2026-05-06T11:05:00Z",
  },

  // ===== 07_modeling_objects =====
  {
    id: "mem:observation:mock:18",
    content: "User Model: 用户偏好简洁的摘要格式，置信度阈值设为0.7",
    memoryType: "observation",
    cognitiveLayer: "semantic",
    beliefStatus: "accepted",
    confidence: 0.92,
    visibility: "private",
    createdBy: "modeling_objects",
    spaceId: MOCK_SPACE_ID,
    tags: ["modeling", "T1", "user_model"],
    attributes: {},
    modelDomain: "user",
    sourceTrustTier: "tier1",
    recordedAt: "2026-05-06T11:10:00Z",
  },
  {
    id: "mem:observation:mock:19",
    content: "Task Model: 检查供应商信用评级的任务状态为pending，预计2026-05-07完成",
    memoryType: "observation",
    cognitiveLayer: "semantic",
    beliefStatus: "accepted",
    confidence: 0.90,
    visibility: "shared",
    createdBy: "modeling_objects",
    spaceId: MOCK_SPACE_ID,
    tags: ["modeling", "T2", "task_model"],
    attributes: { commitment_status: "pending", deadline: "2026-05-07" },
    modelDomain: "task",
    sourceTrustTier: "tier1",
    recordedAt: "2026-05-06T11:12:00Z",
  },
  {
    id: "mem:observation:mock:20",
    content: "World Model: 市场环境约束 — 供应链金融行业当前监管趋严",
    memoryType: "observation",
    cognitiveLayer: "semantic",
    beliefStatus: "accepted",
    confidence: 0.86,
    visibility: "shared",
    createdBy: "modeling_objects",
    spaceId: MOCK_SPACE_ID,
    tags: ["modeling", "T3", "world_model"],
    attributes: { constraint_type: "regulatory" },
    modelDomain: "world",
    sourceTrustTier: "tier1",
    recordedAt: "2026-05-06T11:15:00Z",
  },
  {
    id: "mem:observation:mock:21",
    content: "Self Model: 当前Agent的工具调用成功率为92%，需要关注语义相似度计算的可信度",
    memoryType: "observation",
    cognitiveLayer: "opinion",
    beliefStatus: "accepted",
    confidence: 0.75,
    visibility: "private",
    createdBy: "modeling_objects",
    spaceId: MOCK_SPACE_ID,
    tags: ["modeling", "T4", "self_model"],
    attributes: { tool_reliability: "0.92" },
    modelDomain: "self",
    sourceTrustTier: "tier1",
    recordedAt: "2026-05-06T11:18:00Z",
  },

  // ===== 08_qul_lifecycle =====
  {
    id: "mem:observation:mock:22",
    content: "QUL验证: QUL当前仅支持英文时间约束检测，中文时间约束未实现",
    memoryType: "observation",
    cognitiveLayer: "perception",
    beliefStatus: "accepted",
    confidence: 0.80,
    visibility: "shared",
    createdBy: "qul_eval",
    spaceId: MOCK_SPACE_ID,
    tags: ["qul", "T1", "temporal"],
    attributes: {},
    modelDomain: "world",
    sourceTrustTier: "tier2",
    occurredAt: "2026-05-06T10:00:00Z",
    validFrom: "2026-05-01T00:00:00Z",
    validTo: "2026-12-31T23:59:59Z",
    recordedAt: "2026-05-06T11:20:00Z",
  },
  {
    id: "mem:observation:mock:23",
    content: "QUL约束驱动重排序：按 model_domain×memory_type×scope 三维 boost",
    memoryType: "observation",
    cognitiveLayer: "perception",
    beliefStatus: "pending_review",
    confidence: 0.55,
    visibility: "shared",
    createdBy: "qul_eval",
    spaceId: MOCK_SPACE_ID,
    tags: ["qul", "T3", "reranking"],
    attributes: {},
    modelDomain: "world",
    sourceTrustTier: "tier2",
    recordedAt: "2026-05-06T11:22:00Z",
  },

  // ===== DreamCycle & Forgetting =====
  {
    id: "mem:observation:mock:24",
    content: "DreamCycle 5阶段验证: 复习→反思→巩固→遗忘→洞察",
    memoryType: "observation",
    cognitiveLayer: "opinion",
    beliefStatus: "accepted",
    confidence: 0.83,
    visibility: "shared",
    createdBy: "dream_cycle",
    spaceId: MOCK_SPACE_ID,
    tags: ["dreamcycle", "lifecycle"],
    attributes: {},
    modelDomain: "self",
    sourceTrustTier: "tier1",
    recordedAt: "2026-05-06T11:25:00Z",
  },
  {
    id: "mem:observation:mock:25",
    content: "Ebbinghaus衰减: memory_strength随 days_elapsed 指数下降，小于 retention_threshold 时标记 expired",
    memoryType: "observation",
    cognitiveLayer: "perception",
    beliefStatus: "accepted",
    confidence: 0.87,
    visibility: "shared",
    createdBy: "forgetting",
    spaceId: MOCK_SPACE_ID,
    tags: ["forgetting", "ebb"],
    attributes: { retention_threshold: "0.30" },
    modelDomain: "world",
    sourceTrustTier: "tier1",
    recordedAt: "2026-05-06T11:28:00Z",
  },
];

export const MOCK_STATS: MemoryStats = {
  total: 25,
  by_type: {
    observation: 14,
    opinion: 6,
    entity: 2,
    fragment: 3,
  },
  by_belief: {
    accepted: 20,
    pending_review: 3,
    rejected: 0,
    superseded: 1,
  },
  by_layer: {
    perception: 14,
    semantic: 5,
    opinion: 5,
    procedure: 1,
  },
  space_id: MOCK_SPACE_ID,
  pending_review: 3,
  superseded: 1,
  expired: 0,
  open_contradictions: 2,
  total_corrections: 0,
};

export const MOCK_ACTIVITIES: AuditEntry[] = [
  {
    id: "audit:mock:01",
    memory_type: "observation",
    content: "remember: 客户负面舆情观察",
    belief_status: "accepted",
    superseded_by: null,
    updated_at: "2026-05-06T10:00:02Z",
  },
  {
    id: "audit:mock:02",
    memory_type: "observation",
    content: "remember: DedupGate验证通过",
    belief_status: "accepted",
    superseded_by: null,
    updated_at: "2026-05-06T10:05:02Z",
  },
  {
    id: "audit:mock:03",
    memory_type: "opinion",
    content: "remember: 矛盾检测发现对立结论",
    belief_status: "accepted",
    superseded_by: null,
    updated_at: "2026-05-06T10:22:02Z",
  },
  {
    id: "audit:mock:04",
    memory_type: "opinion",
    content: "supersede: 旧策略被新策略替代",
    belief_status: "superseded",
    superseded_by: "mem:opinion:mock:09",
    updated_at: "2026-05-06T10:30:02Z",
  },
  {
    id: "audit:mock:05",
    memory_type: "observation",
    content: "consolidate: fragment→observation 巩固完成",
    belief_status: "accepted",
    superseded_by: null,
    updated_at: "2026-05-06T10:40:02Z",
  },
  {
    id: "audit:mock:06",
    memory_type: "observation",
    content: "reflect: 发现3个矛盾、1个洞察",
    belief_status: "accepted",
    superseded_by: null,
    updated_at: "2026-05-06T10:50:02Z",
  },
  {
    id: "audit:mock:07",
    memory_type: "observation",
    content: "dream_cycle: 5阶段完成",
    belief_status: "accepted",
    superseded_by: null,
    updated_at: "2026-05-06T11:25:02Z",
  },
];

export const MOCK_CONTRADICTIONS = [
  {
    id: "contra:mock:01",
    description: "供应商信用评级矛盾: D级 vs 非D级",
    severity: "high",
    field: "credit_rating",
    oldValue: "D级",
    newValue: "不是D级",
    involvedNodes: ["mem:opinion:mock:05", "mem:opinion:mock:06"],
    detectedAt: "2026-05-06T10:22:00Z",
  },
  {
    id: "contra:mock:02",
    description: "语义矛盾: 两个分析师对合作前景的意见不一致",
    severity: "medium",
    field: "cooperation_prospect",
    oldValue: "不适合合作",
    newValue: "可以继续合作",
    involvedNodes: ["mem:opinion:mock:05", "mem:opinion:mock:06", "mem:opinion:mock:07"],
    detectedAt: "2026-05-06T10:25:00Z",
  },
];

export const MOCK_RECALL_RESPONSE: RecallResponse = {
  results: MOCK_NODES,
  totalCount: 25,
  edges: [
    { source: "mem:opinion:mock:05", target: "mem:opinion:mock:06", edge_type: "CONTRADICTS" },
    { source: "mem:opinion:mock:08", target: "mem:opinion:mock:09", edge_type: "SUPERSEDES" },
    { source: "mem:fragment:mock:10", target: "mem:observation:mock:12", edge_type: "CONSOLIDATED_INTO" },
    { source: "mem:fragment:mock:11", target: "mem:observation:mock:12", edge_type: "CONSOLIDATED_INTO" },
    { source: "mem:observation:mock:02", target: "mem:observation:mock:01", edge_type: "COG_SUPPORTED_BY" },
    { source: "mem:opinion:mock:09", target: "mem:opinion:mock:08", edge_type: "SUPERSEDES" },
    { source: "mem:observation:mock:12", target: "mem:observation:mock:13", edge_type: "COGNITIVE_RELATES_TO" },
    { source: "mem:observation:mock:15", target: "mem:observation:mock:14", edge_type: "SUMMARIZED_AS" },
    { source: "mem:observation:mock:17", target: "mem:observation:mock:16", edge_type: "PART_OF" },
  ],
};

export const MOCK_REFLECT_RESPONSE: ReflectResponse = {
  taskId: "reflect:mock:001",
  status: "completed",
  results: [],
  totalResults: 5,
  report: {
    totalIterations: 3,
    processedNodes: 10,
    newNodes: 2,
    updatedNodes: 3,
    summary:
      "发现2个高严重度矛盾（信用评级对立），生成1个洞察（多源验证建议），整合3个相关节点。建议人工裁决后更新信念状态。",
    insights: [
      {
        type: "contradiction_pattern",
        description:
          "多位分析师的结论相互矛盾，表明供应商信用评级需要多源验证",
        confidence: 0.82,
        id: "insight:mock:01",
      },
      {
        type: "knowledge_gap",
        description: "缺少2026年Q1供应商的实际履约数据，无法做出准确的最终判断",
        confidence: 0.71,
        id: "insight:mock:02",
      },
    ],
    contradictions: [
      {
        description: "供应商信用评级: D级 vs 非D级 — 两个来源相互矛盾",
        severity: "high",
        involvedNodes: ["mem:opinion:mock:05", "mem:opinion:mock:06"],
        resolved: false,
      },
      {
        description: "语义层面意见不一致: '不适合合作' vs '可以继续合作'",
        severity: "medium",
        involvedNodes: ["mem:opinion:mock:05", "mem:opinion:mock:06", "mem:opinion:mock:07"],
        resolved: false,
      },
    ],
    consolidatedNodes: [
      "mem:observation:mock:12",
      "mem:observation:mock:15",
      "mem:observation:mock:16",
    ],
  },
};
